- .github/workflows/ci.yml
This PR removes the unmaintained `actions-rs/toolchain` and `actions-rs/cargo`. `actions-rs/toolchain` is replaced by `dtolnay/rust-toolchain` and `actions-rs/cargo` by direct invocations of `cargo`. It should fix many CI warnings.
> ci: fix deprecation warnings by removing `actions-rs/cargo` and `actions-rs/toolchain`

- src/uu/mountpoint/src/mountpoint.rs
This PR should make the Windows-related jobs in the CI pass and adds a dummy implementation of `is_mountpoint` for Windows.
> mountpoint: make it compile on Windows

- src/uu/mountpoint/src/mountpoint.rs
- tests/by-util/test_mountpoint.rs
This PR fixes two clippy warnings on Windows about an unused import and an unused variable. Combined with https://github.com/uutils/util-linux/pull/27 it should make the "cargo clippy" tests in the CI pass.
> mountpoint: fix two clippy warnings on Windows

- src/uu/lscpu/src/lscpu.rs
This PR fixes an error from the [never_loop](https://rust-lang.github.io/rust-clippy/master/index.html#/never_loop) clippy lint and should make the "cargo clippy" job in the CI pass (at least on Ubuntu). It also fixes two "unused variable" warnings.
> lscpu: fix `never_loop` lint error

- Cargo.lock
- Cargo.toml
- src/uu/lscpu/src/lscpu.rs
This PR bumps `sysinfo` from `0.30` to `0.31`. It also removes a line in `lscpu` that uses a function from `sysinfo` that no longer exists.
> Bump `sysinfo` and fix compile error in `lscpu`

- src/uu/rev/src/rev.rs
This PR fixes two warnings from `clippy::pedantic`: 
* it uses `==` instead of `!=` in a condition
* it replaces a `match` with `if let`
> rev: fix two pedantic clippy warnings

- tests/common/util.rs
This PR fixes warnings from the [doc_lazy_continuation](https://rust-lang.github.io/rust-clippy/master/index.html#/doc_lazy_continuation) and [ineffective_open_options](https://rust-lang.github.io/rust-clippy/master/index.html#/ineffective_open_options) lints
> tests/common/util.rs: fix clippy warnings

- Cargo.lock
- Cargo.toml
- src/uu/last/Cargo.toml
- src/uu/last/last.md
- src/uu/last/src/last.rs
- src/uu/last/src/main.rs
- src/uu/last/src/platform/mod.rs
- src/uu/last/src/platform/openbsd.rs
- src/uu/last/src/platform/unix.rs
- src/uu/last/src/platform/windows.rs
- tests/by-util/test_last.rs
- tests/tests.rs
I implemented the last utility in https://github.com/uutils/util-linux/issues/18.
**Limitations**
- I only implemented support for Unix
- Several flags from GNU last were not implemented.
- There are some slight output differences between GNU last and this implementation. They can be easily cleared up given more time. For example GNU last prints the relative time since the last crash, while this doesn't do that quite yet.
**Tests**
I added some tests too to go along with the PR.  They are kind of simplistic though in that they only do a check to verify there was some output. The timestamp checks only do a simplistic regex check on the output.
> Add last Utility

- Cargo.lock
- Cargo.toml
- src/uu/setsid/Cargo.toml
- src/uu/setsid/setsid.md
- src/uu/setsid/src/main.rs
- src/uu/setsid/src/setsid.rs
- tests/by-util/test_setsid.rs
- tests/common/util.rs
- tests/fixtures/util/is_atty.sh
- tests/tests.rs
This one is very straight-forward. I did both an implementation using libc to fork and exec directly and one using the std::process::Command interface. I am not sure how much is gained in terms of clarity or safety, given how straight-forward this tool is, let me know which one you prefer =)
The main open questions I have are 1) whether we should first get the handling of the error codes landed in uucore:
```rust
// FIXME: POSIX wants certain exit statuses for specific errors, should
// these be handled by uucore::error? We should be able to just return
// the UError here.
uucore::show_error!(
"failed to execute {}: {}",
executable.to_string_lossy(),
UIoError::from(error)
);
if kind == io::ErrorKind::NotFound {
uucore::error::set_exit_code(127);
} else if kind == …
```
> Add setsid implementation

- tests/by-util/test_last.rs
- tests/by-util/test_setsid.rs
This PR fixes "unused import" warnings on Windows (see https://github.com/uutils/util-linux/actions/runs/11739829667/job/32705131920#step:4:231). Some warnings are fixed by adding `#[cfg(unix)]`, other warnings are fixed by rewriting a test to get rid of the imports.
> tests: fix "unused import" warnings on Windows

- Cargo.lock
- Cargo.toml
- src/uu/lsmem/src/lsmem.rs
This PR bumps `tabled` from `0.16.0` to `0.17.0` and adapts `lsmem` to a renamed struct.
> Bump `tabled` and adapt `lsmem` to a renamed struct

- src/uu/dmesg/src/dmesg.rs
When I tried to use rust `dmesg` program, I found that it hangs during a read of  `/dev/kmsg`. Using `strace` I found few errors.
In order to properly read from /dev/kmsg, 3 things are needed [*]: 
1) open /dev/kmesgs with O_NONBLOCK
2) handle the EAGAIN/WouldBlock error as end of records 
3) treat '\n' (and not '\0') as record separator.
[*] https://www.kernel.org/doc/Documentation/ABI/testing/dev-kmsg
> dmesg: fix a non working support of /dev/kmesg

- Cargo.lock
- Cargo.toml
- README.md
- src/uu/fsfreeze/Cargo.toml
- src/uu/fsfreeze/fsfreeze.md
- src/uu/fsfreeze/src/fsfreeze.rs
- src/uu/fsfreeze/src/main.rs
- tests/by-util/test_fsfreeze.rs
- tests/tests.rs
Add fsfreeze, a Linux-specific tool used to freeze/thaw writes to a
filesystem. It's an extremely simple tool so this should have full
feature-parity.
Also add linux-raw-sys dependency to get the definitions for the ioctl numbers needed by this (and I expect many other block device tools to need the same).
> fsfreeze: add tool (+ linux-raw-sys dependency)

- tests/by-util/test_dmesg.rs
This PR removes a `format!` in a test to fix a warning from the [useless_format](https://rust-lang.github.io/rust-clippy/master/index.html#useless_format) lint.
> dmesg: remove useless `format!` in test

- src/uu/lscpu/src/lscpu.rs
This PR fixes the code formatting because `fmt` stopped doing it due to a string that was too long. The PR also removes an irrelevant sentence from the help text.
> lscpu: fix code formatting & remove sentence from help text

- Cargo.lock
- Cargo.toml
- tests/common/random.rs
This PR bumps `rand` from `0.8.5` to `0.9.0` and adapts `tests/common/random.rs` to the API changes.
> Bump `rand` & adapt tests to its API changes

- tests/by-util/test_lscpu.rs
This PR renames a test function because the original name contains a typo and isn't very descriptive.
> lscpu: rename test function

- Cargo.lock
- Cargo.toml
- src/uu/lscpu/Cargo.toml
- src/uu/lscpu/src/lscpu.rs
- tests/by-util/test_lscpu.rs
> lscpu: Add option --json

- src/uu/lscpu/src/lscpu.rs
- tests/by-util/test_lscpu.rs
`lscpu` should be capable of outputting nested information. When using human-readable output this is achieved simply using indentation, where as in JSON mode nested fields go under the `children` property.
- Modified `CpuInfo` to be a recursive structure, allowing for nesting of entries through the `children` property.
- Moved output logic into its own function, adding support for printing out nested values, and ensuring the values on the right are aligned to the same column.
- Implemented a helper function for extracting arbitrary values from `/proc/cpuinfo`, using a dynamically constructed Regex.
- Added support for some basic fields like Vendor ID, CPU Family and Model, to illustrate how the aforementioned changes can be used in action.
- Added missing `-J` shorthand counterpart to the …
> `lscpu`: Support extracting and outputting nested fields

- src/uu/lscpu/src/lscpu.rs
This PR removes the third param of `CpuInfo::new()` because we always pass `None` as value.
> lscpu: simplify signature of `CpuInfo::new()`

- Cargo.lock
- Cargo.toml
- src/uu/lslocks/Cargo.toml
- src/uu/lslocks/lslocks.md
- src/uu/lslocks/src/lslocks.rs
- src/uu/lslocks/src/main.rs
- tests/by-util/test_lslocks.rs
- tests/tests.rs
Didn't have much time to spend on this but managed to cobble together a rudimentary starting point for the full `lslocks` implementation.
So far it only relies on information gathered directly from `/proc/locks`, without diving deeper into `/proc/<pid>/fdinfo` to parse out information regarding the actual file being locked (such as file path and size).
Output formatting has been implemented in a way that should be extensible enough to later implement these missing features.
Output as of right now:
```
COMMAND         PID   TYPE  MODE  M START      END       
spotify         1663  POSIX WRITE 0 1073741824 1073742335
spotify         1663  POSIX WRITE 0 1073741824 1073742335
kioworker       11229 POSIX WRITE 0 11229      11229     
kioworker       11229 POSIX READ  0 0          0 …
```
> Add partial implementation of `lslocks`

- Cargo.lock
- Cargo.toml
- src/uu/mcookie/Cargo.toml
- src/uu/mcookie/mcookie.md
- src/uu/mcookie/src/main.rs
- src/uu/mcookie/src/mcookie.rs
- tests/by-util/test_mcookie.rs
- tests/tests.rs
This is a very simple one. It generates a random MD5 value, optionally using provided files as seed data for the hash.
Only two minor things are "missing":
- The `-m` parameter currently only accepts the size as an integer of bytes, not in human-readable form (`123 KiB` etc.). I can see there's a couple crates that can handle parsing sizes, I'm just not sure if there's a preference for any particular one. Let me know if there is one, or if there's some existing functionality for this somewhere in `uutils`.
- In verbose mode, the original `mcookie` will output something along the lines of: `Got X bytes from getrandom() function`. Since we're using `rand::rng()` for our RNG, we don't actually know what source of randomness is being used at runtime. Of course its possible to explicitly …
> Implement `mcookie`

- .gitignore
- Cargo.lock
- Cargo.toml
- src/uu/chcpu/Cargo.toml
- src/uu/chcpu/chcpu.md
- src/uu/chcpu/src/chcpu.rs
- src/uu/chcpu/src/errors.rs
- src/uu/chcpu/src/main.rs
- src/uu/chcpu/src/sysfs.rs
> Implemented `chcpu`

- tests/by-util/test_lslocks.rs
- tests/by-util/test_mcookie.rs
This PR fixes two "unused import" warnings in the tests (see, for example, https://github.com/uutils/util-linux/actions/runs/13988296791/job/39166347016#step:4:275). One warning is solved by removing the import, the other by making the import linux-only.
> mcookie, lslocks: fix "unused import" warnings in tests

- build.rs
This PR removes some `coreutils` stuff from `build.rs` that's not needed in `util-linux`.
> build.rs: remove `coreutils` stuff

- src/uu/mcookie/src/mcookie.rs
- src/uu/mcookie/src/size.rs
- tests/by-util/test_mcookie.rs
fixes #257 
took inspiration from CacheSize https://github.com/uutils/util-linux/blob/390d074712bda9815129bc017124a6d7422867db/src/uu/lscpu/src/sysfs.rs#L90C1-L138C1
> mcookie: add support for human-readable sizes with -m option

- src/uu/mcookie/src/mcookie.rs
- tests/by-util/test_mcookie.rs
fixes #264 
Fixes an infinite loop when `mcookie` reads from `/dev/random` or `/dev/urandom` without a `--max-size`.
The issue occurred because `read_to_end()` was used on these non-terminating character devices.
This PR checks if the input file is a character device. If so, and no `--max-size` is given, it reads only a limited number of bytes (1024) instead of attempting to read indefinitely. This aligns behavior with the original `mcookie`.
Tested successfully with `/dev/random` and `/dev/urandom`.
> mcookie - fix providing /dev/random or /dev/urandom as file leads to infinite loop

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/uu/lsipc/Cargo.toml
- src/uu/lsipc/after-help.txt
- src/uu/lsipc/lsipc.md
- src/uu/lsipc/src/column.rs
- src/uu/lsipc/src/display.rs
- src/uu/lsipc/src/errors.rs
- src/uu/lsipc/src/lsipc.rs
- src/uu/lsipc/src/main.rs
- src/uu/lsipc/src/message_queue.rs
- src/uu/lsipc/src/semaphore.rs
- src/uu/lsipc/src/shared_memory.rs
- src/uu/lsipc/src/smartcols.rs
- src/uu/lsipc/src/utils.rs
Dependencies I had to do:
- I created a new [crate `smartcols-sys`](https://crates.io/crates/smartcols-sys).
- I created [this PR for libc](https://github.com/rust-lang/libc/pull/4301).
- I created [this PR for util-linux](https://github.com/util-linux/util-linux/pull/3462).
Closes #19.
> Implemented `lsipc`

- tests/common/util.rs
This PR fixes some warnings from the [doc_overindented_list_items](https://rust-lang.github.io/rust-clippy/master/index.html#doc_overindented_list_items) lint.
> clippy: fix warnings from `doc_overindented_list_items` lint

- src/uu/mcookie/src/mcookie.rs
- tests/by-util/test_mcookie.rs
Solves #284.
Also sets a default limit of 4096 bytes when -m is not specified as in original.
> mcookie: fix max size

- Cargo.lock
- Cargo.toml
- src/uu/mesg/Cargo.toml
- src/uu/mesg/src/mesg.rs
This PR bumps `nix` from `0.29.0` to `0.30.1` and adapts `mesg` to the API changes in `nix`.
> Bump nix & adapt to its API changes

- Cargo.lock
- Cargo.toml
This PR removes the unused `procfs` dependency. It probably conflicts with https://github.com/uutils/util-linux/pull/332
> Remove unused `procfs` dependency

- Cargo.lock
- Cargo.toml
- build.rs
This PR bumps `phf_codegen` from `0.11.2` to `0.12.1` and fixes a "does not live long enough" error in `build.rs`.
> Bump `phf_codegen` & fix compilation error

- Cargo.lock
- Cargo.toml
This PR manually bumps `linux-raw-sys` from `0.9.0` to `0.10.0` because renovate fails with an "Artifact update problem" in https://github.com/uutils/util-linux/pull/331.
> Bump `linux-raw-sys` from `0.9.0` to `0.10.0`

- Cargo.lock
- Cargo.toml
- src/uu/last/Cargo.toml
- src/uu/last/src/last.rs
- src/uu/last/src/platform/unix.rs
- tests/by-util/test_last.rs
Resolves https://github.com/uutils/util-linux/issues/213
> feat(last): add --since and --until

- Cargo.lock
- Cargo.toml
This PR manually bumps `dns-lookup` from `2.0.4` to `3.0.0` because renovate fails with an "Artifact update problem" in https://github.com/uutils/util-linux/pull/373
> Bump `dns-lookup` from `2.0.4` to `3.0.0`

- Cargo.lock
- Cargo.toml
- src/uu/last/src/platform/unix.rs
This PR bumps `uucore` from `0.1.0` to `0.2.2` and adapts `last` to an API change in `uucore::utmpx`.
> Bump `uucore` & adapt `last` to API change
